{ config, lib, ... }:

# Runs atticd, the binary cache the ephemeral BinaryLane "rebuild the world"
# build server pushes CPU-tuned closures into, and the rest of the fleet
# pulls from ahead of cache.nixos.org (see modules/core/build-tuning.nix and
# common.nix's substituters). See docs/roadmap.md's "Ephemeral BinaryLane
# build server" section for the full design.
#
# Exposed publicly at attic.jupiter.au via the existing Cloudflare Tunnel
# (lib/site.nix's tunnel.ingress) rather than only on the home LAN, since
# both the pallene build server (BinaryLane's public cloud) and himalia
# (roams) need to reach it from outside the house. Access control is atticd's
# own RS256-signed token auth, not network location.

let
  cfg = config.jupiter.services.attic;
in
{
  options.jupiter.services.attic = {
    enable = lib.mkEnableOption "the atticd binary cache server";

    port = lib.mkOption {
      type = lib.types.port;
      default = 8080;
      description = "Port atticd listens on (proxied by the Cloudflare Tunnel — see lib/site.nix).";
    };

    storagePath = lib.mkOption {
      type = lib.types.path;
      default = "/tank/services/attic";
      description = ''
        Where atticd stores its cache objects and sqlite database. Lives on
        tank — bulk, reproducible state (every object here can just be
        rebuilt), so it's deliberately NOT part of the offsite restic set
        (see docs/01-architecture.md). Must exist before atticd starts:
        `zfs create -p tank/services/attic`, matching the other by-hand tank
        datasets in modules/storage/zfs-nas.nix.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # sopsFile defaults to sops.defaultSopsFile (set in modules/common.nix).
    # Generated by `make gen-secrets` (scripts/gen-secrets.sh) — an RS256 JWT
    # signing key is atticd's own service-to-service secret, not tied to any
    # external account.
    sops.secrets.attic_server_token_secret = { };

    services.atticd = {
      enable = true;
      environmentFile = config.sops.secrets.attic_server_token_secret.path;
      settings = {
        listen = "[::]:${toString cfg.port}";
        database.url = "sqlite://${cfg.storagePath}/server.db?mode=rwc";
        storage = {
          type = "local";
          path = "${cfg.storagePath}/storage";
        };
      };
    };

    # LAN-only in practice (the Cloudflare Tunnel reaches in without an open
    # port), but harmless to allow directly too for same-network clients.
    networking.firewall.allowedTCPPorts = [ cfg.port ];
  };
}
