.PHONY: test-ganymede test-himalia test-europa test-metis test-adrastea test-amalthea test-thebe test-callisto \
        update check build-all build-mx4300 \
        fmt fmt-check tf-plan-unifi tf-apply-unifi tf-plan-cloudflare tf-apply-cloudflare \
        boot-smoke-ganymede boot-smoke-himalia boot-smoke-europa boot-smoke-metis boot-smoke-adrastea \
        boot-smoke-amalthea boot-smoke-thebe gen-secrets docs-modules docs-modules-check

# Build all machines and firmware (useful for verifying everything compiles)
build-all:
	@echo "Building ganymede (compute node)..."
	nix build .#nixosConfigurations.ganymede.config.system.build.toplevel
	@echo "Building himalia (laptop)..."
	nix build .#nixosConfigurations.himalia.config.system.build.toplevel
	@echo "Building europa (NAS)..."
	nix build .#nixosConfigurations.europa.config.system.build.toplevel
	@echo "Building dashboard kiosks (metis, adrastea, amalthea, thebe)..."
	nix build .#nixosConfigurations.metis.config.system.build.toplevel
	nix build .#nixosConfigurations.adrastea.config.system.build.toplevel
	nix build .#nixosConfigurations.amalthea.config.system.build.toplevel
	nix build .#nixosConfigurations.thebe.config.system.build.toplevel
	@echo "Building callisto (diskless compute)..."
	nix build .#nixosConfigurations.callisto.config.system.build.toplevel
	$(MAKE) build-mx4300
	@echo "All builds completed successfully!"

# Build the OpenWrt firmware with injected secrets
build-mx4300:
	@echo "Injecting secrets into OpenWrt config templates..."
	sops exec-env secrets/secrets.yaml 'envsubst < hosts/parents-house/access-points/mx4300-files/etc/uci-defaults/99-mesh-setup.sh.tmpl > hosts/parents-house/access-points/mx4300-files/etc/uci-defaults/99-mesh-setup.sh'
	sops exec-env secrets/secrets.yaml 'envsubst < hosts/parents-house/wyze-cams/wz_mini.conf.tmpl > hosts/parents-house/wyze-cams/wz_mini.conf'
	@echo "Building Linksys MX4300 OpenWrt Firmware..."
	nix build .#mx4300-firmware
	@echo "Cleaning up plaintext configs (do not commit these!)..."
	rm -f hosts/parents-house/access-points/mx4300-files/etc/uci-defaults/99-mesh-setup.sh
	rm -f hosts/parents-house/wyze-cams/wz_mini.conf

# Build and run a QEMU virtual machine for a specific host
# Usage: make test-ganymede
test-%:
	@echo "Building and launching VM for host: $*..."
	nixos-rebuild build-vm --flake .#$*
	@echo "Starting VM... (Press Ctrl+A then X to exit the QEMU console)"
	./result/bin/run-$*-vm -m 2048 -smp 2

# Headless boot smoke test: build the host VM and assert it reaches multi-user,
# then shut it down (no interactive console). Used by CI; needs /dev/kvm.
# Usage: make boot-smoke-himalia
boot-smoke-%:
	./scripts/boot-smoke.sh $* 300

# Generate random machine-to-machine credentials into sops (idempotent).
# Service passwords are never chosen by hand — see scripts/gen-secrets.sh.
gen-secrets:
	./scripts/gen-secrets.sh

# Update flake locks
update:
	nix flake update

# Check flake evaluation
check:
	nix flake check

# Format all Nix files with the flake's formatter (nixfmt-rfc-style)
fmt:
	nix fmt .

# Verify formatting without writing changes (used by CI)
fmt-check:
	nix run nixpkgs#nixfmt-rfc-style -- --check .

# Regenerate docs/module-options.md — the `jupiter.*` options reference,
# rendered from the `mkOption { description = ...; }` strings via
# nixos-render-docs (see lib/module-options.nix). Run after adding/changing
# any jupiter.* option.
docs-modules:
	nix build .#module-options-md --no-link --print-out-paths | xargs -I{} \
		sh -c 'printf "%s\n\n" "<!-- Generated by \`make docs-modules\` (lib/module-options.nix). Do not edit by hand. -->" > docs/module-options.md && cat {} >> docs/module-options.md'

# Verify docs/module-options.md matches what `make docs-modules` would produce
# (used by CI to catch option changes that weren't regenerated).
docs-modules-check:
	@cp docs/module-options.md /tmp/module-options.md.orig
	@$(MAKE) docs-modules
	@diff -q /tmp/module-options.md.orig docs/module-options.md > /dev/null || \
		(echo "docs/module-options.md is stale — run 'make docs-modules' and commit the result." && \
		 mv /tmp/module-options.md.orig docs/module-options.md && exit 1)
	@rm -f /tmp/module-options.md.orig

# ---------------------------------------------------------------------------
# Terraform / terranix
#
# terranix renders the HCL in terraform/<stack>/default.nix to a config.tf.json,
# which we drop next to it (terraform reads *.tf.json and ignores *.nix). State
# lives in terraform/<stack>/ (gitignored). Provider credentials are pulled from
# the encrypted secrets and exported as TF_VAR_* via `sops exec-env`.
#
# Required secret keys (secrets/secrets.yaml):
#   unifi          -> unifi_password
#   cloudflare     -> cloudflare_api_token   (NOTE: add this; not yet present)
# ---------------------------------------------------------------------------

# $(1) = stack name (unifi|cloudflare), $(2) = terraform subcommand (plan|apply)
define tf-run
	@echo "Rendering terranix config for '$(1)'..."
	nix build .#terranix-$(1) --no-link --print-out-paths | xargs -I{} install -m600 {} terraform/$(1)/config.tf.json
	cd terraform/$(1) && terraform init -input=false
	@echo "Running 'terraform $(2)' for '$(1)' (secrets injected via sops)..."
	sops exec-env secrets/secrets.yaml 'cd terraform/$(1) && \
		TF_VAR_unifi_password="$$unifi_password" \
		TF_VAR_cloudflare_api_token="$$cloudflare_api_token" \
		terraform $(2)'
endef

tf-plan-unifi:
	$(call tf-run,unifi,plan)

tf-apply-unifi:
	$(call tf-run,unifi,apply)

tf-plan-cloudflare:
	$(call tf-run,cloudflare,plan)

tf-apply-cloudflare:
	$(call tf-run,cloudflare,apply)
