{
  config,
  lib,
  pkgs,
  ...
}:

# jupiterOS Arcade — the Pegasus frontend layer of the kiosk arcade session.
#
# This module owns Pegasus itself: the package, the theme, the gamer user's
# Pegasus config seeding (game_dirs.txt + settings.txt), and the emulator
# catalogue. It does NOT know how games are stored or launched — collection
# modules contribute their Pegasus-readable collection roots to
# `jupiter.arcade.gameDirs` (see modules/desktop/exodos.nix for the eXo
# collections: NFS + overlayfs + exo-launch), and each collection's
# metadata.pegasus.txt carries its own `launch:` line. The session unit
# (jupiter-arcade.service, gamescope + pegasus-fe on tty1) is generated by
# modules/desktop/dashboard-gaming.nix's `arcade` modeSpecs entry.
#
# History: this module used to implement issue #30's on-demand ROM loading
# (pegasus-rom-launch dispatcher + bubbletea-game-loader TUI + a read-only
# NFS mount of /tank/archive/retro). That stack could never launch an eXo
# game (extraction flattened the zip's directory tree, the dispatcher wasn't
# on the session's PATH, and the metadata pointed at directories), so issue
# #40 replaced it with the exo-launch architecture; the dispatcher and TUI
# now live in scripts/deprecated/. When 1G1R console collections return,
# wire them in as another gameDirs contributor rather than reviving a global
# launcher script — Pegasus has no such setting (its settings.txt parser
# silently drops unknown keys like `launcher.script`).

let
  cfg = config.jupiter.arcade;

  # Custom Pegasus theme: "jupiterOS arcade". Touch-friendly, Catppuccin Mocha
  # palette. Files live in the Nix store and are symlinked into the gamer
  # user's themes dir via tmpfiles.
  jupiterArcadeTheme = pkgs.stdenv.mkDerivation {
    name = "jupiteros-arcade-theme";
    src = ./jupiteros-arcade-theme;
    installPhase = ''
      runHook preInstall
      mkdir -p $out
      cp -r ./. $out/
      runHook postInstall
    '';
  };
in
{
  options.jupiter.arcade = {
    enable = lib.mkEnableOption "jupiterOS Arcade (Pegasus frontend for the kiosk gaming session)";

    gameDirs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = ''
        Directories Pegasus scans for collections (one metadata.pegasus.txt
        per directory), written to the session user's game_dirs.txt on every
        boot. Collection modules contribute entries (list options
        concatenate): modules/desktop/exodos.nix adds its merged overlay
        roots. Managed declaratively — hand-edits to game_dirs.txt are
        overwritten at the next boot/switch.
      '';
    };

    sessionUser = lib.mkOption {
      type = lib.types.str;
      default = "gamer";
      description = "User that owns the Pegasus config and runs the arcade session";
    };

    theme = lib.mkOption {
      type = lib.types.str;
      default = "jupiteros-arcade";
      description = "Pegasus theme name (must be installed in the user's themes dir)";
    };

    extraEmulators = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = with pkgs; [
        retroarch
        scummvm
      ];
      description = ''
        Emulators installed alongside Pegasus for non-eXo collections.
        dosbox-staging/dosbox-x come from modules/desktop/exodos.nix with the
        collections that need them.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # --- Packages: Pegasus frontend + theme + emulators ----------------------
    environment.systemPackages = [
      pkgs.pegasus-frontend
      jupiterArcadeTheme
      pkgs.xterm
    ]
    ++ cfg.extraEmulators;

    users.users.${cfg.sessionUser} = {
      initialHashedPassword = "!"; # login via HA only
      extraGroups = [
        "video"
        "render"
        "input"
        "audio"
      ];
    };

    systemd.tmpfiles.rules = [
      "d /home/${cfg.sessionUser}/.config/pegasus-frontend 0755 ${cfg.sessionUser} users -"
      "d /home/${cfg.sessionUser}/.config/pegasus-frontend/themes 0755 ${cfg.sessionUser} users -"
      # L+ forces (re)create so a theme change in a future deploy propagates
      # without needing to wipe the user dir.
      "L+ /home/${cfg.sessionUser}/.config/pegasus-frontend/themes/jupiteros-arcade - - - - ${jupiterArcadeTheme}"
    ];

    # --- Pegasus config seeding ----------------------------------------------
    # game_dirs.txt is where Pegasus discovers collections (one path per
    # line, `#` comments) — NOT settings.txt, which only holds theme/UI
    # state. game_dirs.txt is rewritten every boot from cfg.gameDirs so the
    # kiosk always matches the declared collection set (self-healing after
    # hand-edits — that's how amalthea ended up showing 2 of 3 collections).
    # settings.txt is seeded only when absent: Pegasus rewrites it on exit
    # with the user's UI choices, and clobbering those on every boot would
    # revert e.g. a theme the user picked in the UI.
    systemd.services.pegasus-config-seed = {
      description = "Seed Pegasus config (game_dirs + settings) for ${cfg.sessionUser}";
      wantedBy = [ "multi-user.target" ];
      # Runs before the session can start at boot; jupiter-arcade.service is
      # only started on demand (HA select), by which point this has run.
      before = [ "jupiter-arcade.service" ];
      path = [
        pkgs.coreutils
        pkgs.gnused
      ];
      serviceConfig = {
        Type = "oneshot";
        User = cfg.sessionUser;
        Group = "users";
      };
      script =
        let
          gameDirsFile = pkgs.writeText "pegasus-game_dirs.txt" ''
            # Managed by modules/desktop/arcade.nix (jupiter.arcade.gameDirs).
            # Hand-edits are overwritten on every boot/switch.
            ${lib.concatStringsSep "\n" cfg.gameDirs}
          '';
          settingsSeedFile = pkgs.writeText "pegasus-settings.txt" ''
            # Seeded by modules/desktop/arcade.nix; Pegasus rewrites this file
            # on exit with the user's UI choices, which then persist.
            general.theme: themes/${cfg.theme}
          '';
        in
        ''
          set -eu
          CONFIG_DIR="''${XDG_CONFIG_HOME:-/home/${cfg.sessionUser}/.config}/pegasus-frontend"
          mkdir -p "$CONFIG_DIR"

          install -m 0644 ${gameDirsFile} "$CONFIG_DIR/game_dirs.txt"

          # Seed the theme on first run only; drop legacy keys from the old
          # issue-30 stack (launcher.script / assets.directory /
          # collections.directory are not Pegasus settings — Pegasus itself
          # deletes them when it saves, but a stale seed may still carry them).
          SETTINGS="$CONFIG_DIR/settings.txt"
          if [ ! -f "$SETTINGS" ]; then
            install -m 0644 ${settingsSeedFile} "$SETTINGS"
          else
            sed -i '/^launcher\.script:/d;/^assets\.directory:/d;/^collections\.directory:/d' "$SETTINGS"
          fi
        '';
    };
  };
}
