{
  config,
  lib,
  pkgs,
  ...
}:

# jupiterOS Arcade — the Pegasus frontend layer of the kiosk arcade session.
#
# This module owns Pegasus itself: the package, the theme, the gamer user's
# Pegasus config seeding (game_dirs.txt + settings.txt), and the emulator
# catalogue. It does NOT know how games are stored or launched — collection
# modules contribute their Pegasus-readable collection roots to
# `jupiter.arcade.gameDirs` (see modules/desktop/exodos.nix for the eXo
# collections: NFS + overlayfs + exo-launch), and each collection's
# metadata.pegasus.txt carries its own `launch:` line. The session unit
# (jupiter-arcade.service, gamescope + pegasus-fe on tty1) is generated by
# modules/desktop/dashboard-gaming.nix's `arcade` modeSpecs entry.
#
# History: this module used to implement issue #30's on-demand ROM loading
# (pegasus-rom-launch dispatcher + bubbletea-game-loader TUI + a read-only
# NFS mount of /tank/archive/retro). That stack could never launch an eXo
# game (extraction flattened the zip's directory tree, the dispatcher wasn't
# on the session's PATH, and the metadata pointed at directories), so issue
# #40 replaced it with the exo-launch architecture; the dispatcher and TUI
# now live in scripts/deprecated/. When 1G1R console collections return,
# wire them in as another gameDirs contributor rather than reviving a global
# launcher script — Pegasus has no such setting (its settings.txt parser
# silently drops unknown keys like `launcher.script`).

let
  cfg = config.jupiter.arcade;

  # Shared session-ladder machinery + the arcade slice definition (W4c):
  # the slice caps the arcade PLANE on every host it exists on.
  inherit (import ../lib.nix { inherit config lib pkgs; })
    jupiterArcadeSlice
    ;

  # Custom Pegasus theme: "jupiterOS arcade". Touch-friendly, Catppuccin Mocha
  # palette. Files live in the Nix store and are symlinked into the gamer
  # user's themes dir via tmpfiles.
  jupiterArcadeTheme = pkgs.stdenv.mkDerivation {
    name = "jupiteros-arcade-theme";
    src = ./jupiteros-arcade-theme;
    installPhase = ''
      runHook preInstall
      mkdir -p $out
      cp -r ./. $out/
      runHook postInstall
    '';
  };

  # W4c: the Pegasus third-party providers this fleet knows about
  # (research/notes/interim-report-pegasus-metadata-root-cause-fight:
  # Provider.h ships `bool m_enabled = true;` — every provider is ON until
  # an explicit `providers.<codename>.enabled: false` line lands in
  # settings.txt). The collections arrive exclusively through the
  # declared game_dirs.txt (Pegasus metadata + kiosk-side generators);
  # leaving Steam/GOG/ES2/… enabled beside them is the Skyscraper
  # "mish-mash" precondition — phantom collections injected next to the
  # 64 declared dirs. providersEnabled opts named providers back in.
  knownPegasusProviders = [
    "steam"
    "gog"
    "es2"
    "android_apps"
    "launchbox"
    "logiqx"
    "lutris"
    "playnite"
    "skraper"
  ];

  disabledPegasusProviders = builtins.filter (
    p: !builtins.elem p cfg.providersEnabled
  ) knownPegasusProviders;

  providerDisableLines = pkgs.writeText "pegasus-providers-off.txt" (
    lib.concatStringsSep "\n" (map (p: "providers.${p}.enabled: false") disabledPegasusProviders)
  );

  # OnFailure observer for the session unit. Reaching here means the
  # session unit FAILED (with Restart=always + explicit start limits,
  # that is the start-limit exhaustion: a crash-looping session). An
  # earlier revision escalated by REBOOTING the host (3 failed ladders
  # -> rescue console), but that is wrong for any host with a second
  # job: callisto runs the fleet Postgres, the MQTT broker and shared
  # builds beside its arcade, and on 2026-08-31 a Pegasus start timeout
  # (Type=notify, the 180 s start budget) tripped OnFailure on EVERY
  # boot and reboot-looped the serving host indefinitely — the
  # boot-count guard never fired because /var/lib is impermanent, the
  # counter reset each boot. A game frontend is never worth a host
  # power-cycle: this rung only records the failure episode (journal +
  # counter file, cleared by the launcher on the first good READY);
  # host recovery is an operator decision.
  arcadeFailureScript = pkgs.writeShellScript "jupiter-arcade-failure" ''
    set -eu
    DIR=/var/lib/jupiter-arcade
    mkdir -p "$DIR"
    n=$(( $(cat "$DIR/failure-count" 2>/dev/null || echo 0) + 1 ))
    echo "$n" > "$DIR/failure-count"
    echo "jupiter-arcade failure episode #$n (session unit entered failed state; host stays up)"
  '';
in
{
  options.jupiter.arcade = {
    enable = lib.mkEnableOption "jupiterOS Arcade (Pegasus frontend for the kiosk gaming session)";

    gameDirs = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = ''
        Directories Pegasus scans for collections (one metadata.pegasus.txt
        per directory), written to the session user's game_dirs.txt on every
        boot. Collection modules contribute entries (list options
        concatenate): modules/desktop/exodos.nix adds its merged overlay
        roots. Managed declaratively — hand-edits to game_dirs.txt are
        overwritten at the next boot/switch.
      '';
    };

    sessionUser = lib.mkOption {
      type = lib.types.str;
      default = "gamer";
      description = "User that owns the Pegasus config and runs the arcade session";
    };

    theme = lib.mkOption {
      type = lib.types.str;
      default = "jupiteros-arcade";
      description = "Pegasus theme name (must be installed in the user's themes dir)";
    };

    extraEmulators = lib.mkOption {
      type = lib.types.listOf lib.types.package;
      default = with pkgs; [
        retroarch
        scummvm
      ];
      description = ''
        Emulators installed alongside Pegasus for non-eXo collections.
        dosbox-staging/dosbox-x come from modules/desktop/exodos.nix with the
        collections that need them.
      '';
    };

    # --- W4c kiosk operability spec (plan §6.H) -----------------------------

    watchdogAndLadder = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Supervise the arcade session unit with the full recovery ladder:
        the launcher wrapper as a Type=notify main process asserting
        READY=1 when the frontend reports menu-accepting-input,
        WatchdogSec armed, Restart=always with explicit start limits
        (6 per 300 s — not the upstream 5-per-10 s that parks a
        crash-looping cabinet dead in ~12 s), and an OnFailure
        observer that records the failure episode without touching the
        host (an earlier revision rebooted — removed after it
        reboot-looped callisto, the serving host, on a Pegasus start
        timeout). The ladder numbers live in modules/lib.nix
        (sessionLadder) with their rationale.
      '';
    };

    recycleCalendar = lib.mkOption {
      type = lib.types.str;
      default = "*-*-* 05:00:00";
      description = ''
        Nightly session recycle (systemd calendar expression), the
        mechanism-backed answer to the documented gamescope degradation
        (exponential kernel-slab leak after ~15 h — research note
        gamescope-degradation-is-documented-exponential-kernel-slab-leak-after-15h-reboo).
        <literal>try-restart</literal>: a kiosk whose session is
        down (dashboard mode) is left alone. Scheduled at 05:00 by
        default — deliberately AWAY from the 03:00-class DAT/scan
        maintenance window so the two cheapest defences never collide
        on europa's two cores (plan §6.A capacity rule).
      '';
    };

    providersEnabled = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = ''
        Pegasus third-party providers to LEAVE ENABLED (by codename:
        steam, gog, es2, android_apps, launchbox, logiqx, lutris,
        playnite, skraper). Every provider ships enabled-by-default
        (Provider.h: <literal>bool m_enabled = true;</literal>) and
        settings.txt is seed-once, so the mish-mash exposure never
        self-heals; this module re-asserts
        <literal>providers.&lt;name&gt;.enabled: false</literal> for
        every provider NOT listed here at every boot — the declared
        collection set (game_dirs.txt) stays the only source unless an
        operator explicitly opts a provider back in. Default: none —
        the collections arrive through the declared dirs only.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # --- Packages: Pegasus frontend + theme + emulators ----------------------
    environment.systemPackages = [
      pkgs.pegasus-frontend
      jupiterArcadeTheme
      pkgs.xterm
    ]
    ++ cfg.extraEmulators;

    users.users.${cfg.sessionUser} = {
      initialHashedPassword = "!"; # login via HA only
      extraGroups = [
        "video"
        "render"
        "input"
        "audio"
      ];
    };

    systemd.tmpfiles.rules = [
      "d /home/${cfg.sessionUser}/.config/pegasus-frontend 0755 ${cfg.sessionUser} users -"
      "d /home/${cfg.sessionUser}/.config/pegasus-frontend/themes 0755 ${cfg.sessionUser} users -"
      # L+ forces (re)create so a theme change in a future deploy propagates
      # without needing to wipe the user dir.
      "L+ /home/${cfg.sessionUser}/.config/pegasus-frontend/themes/jupiteros-arcade - - - - ${jupiterArcadeTheme}"
      # W4c: the failure-ladder counter directory — gamer-writable because
      # the session launcher (User=${cfg.sessionUser}) clears the counter
      # on the first good READY; the escalation unit (root) increments it.
      "d /var/lib/jupiter-arcade 0755 ${cfg.sessionUser} users -"
    ];

    # --- W4c: the arcade plane's resource slice + recovery ladder ----------
    systemd.slices."jupiter-arcade" = jupiterArcadeSlice;

    # Ladder contribution to the SHARED session unit name: dashboard-gaming
    # (kiosks, on-demand) and arcade-console (boot-default) both generate
    # `jupiter-arcade.service` from modules/lib.nix's supervised shape;
    # this module adds the arcade-plane Slice and the OnFailure rung on
    # every host that runs the arcade (both import this module).
    systemd.services.jupiter-arcade = lib.mkIf cfg.watchdogAndLadder {
      # Cap the session plane (gamescope + pegasus + launched emulators
      # inherit the session cgroup) — the kiosk half of the slice the
      # europa webapp also joins.
      serviceConfig.Slice = "jupiter-arcade.slice";
      # The ladder's failure observer: reaching failed state (with
      # Restart=always + explicit start limits, that is start-limit
      # exhaustion) records the episode in the journal and the counter
      # file. Deliberately does NOT reboot — see arcadeFailureScript.
      unitConfig.OnFailure = [ "jupiter-arcade-failure.service" ];
    };

    systemd.services.jupiter-arcade-failure = lib.mkIf cfg.watchdogAndLadder {
      description = "jupiterOS Arcade failure observer (records the episode; host stays up)";
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${arcadeFailureScript}";
      };
    };

    # Nightly session recycle (W4c): try-restart at recycleCalendar —
    # only a LIVE session recycles (kiosks sitting on the dashboard are
    # untouched), scheduled away from the DAT/scan maintenance window.
    systemd.timers."jupiter-arcade-recycle" = lib.mkIf cfg.watchdogAndLadder {
      description = "Nightly jupiterOS Arcade session recycle (gamescope leak mitigation)";
      wantedBy = [ "timers.target" ];
      timerConfig = {
        OnCalendar = cfg.recycleCalendar;
        Persistent = false;
        Unit = "jupiter-arcade-recycle.service";
      };
    };
    systemd.services."jupiter-arcade-recycle" = lib.mkIf cfg.watchdogAndLadder {
      description = "Recycle the jupiterOS Arcade session (try-restart)";
      serviceConfig = {
        Type = "oneshot";
        ExecStart = "${pkgs.systemd}/bin/systemctl try-restart jupiter-arcade.service";
      };
    };

    # --- Pegasus config seeding ----------------------------------------------
    # game_dirs.txt is where Pegasus discovers collections (one path per
    # line, `#` comments) — NOT settings.txt, which only holds theme/UI
    # state. game_dirs.txt is rewritten every boot from cfg.gameDirs so the
    # kiosk always matches the declared collection set (self-healing after
    # hand-edits — that's how amalthea ended up showing 2 of 3 collections).
    # settings.txt is seeded only when absent: Pegasus rewrites it on exit
    # with the user's UI choices, and clobbering those on every boot would
    # revert e.g. a theme the user picked in the UI — EXCEPT the provider
    # defaults (W4c), which are re-asserted at every boot exactly because
    # seed-once settings never self-heal and every provider ships enabled.
    systemd.services.pegasus-config-seed = {
      description = "Seed Pegasus config (game_dirs + settings + provider defaults) for ${cfg.sessionUser}";
      wantedBy = [ "multi-user.target" ];
      # Runs before the session can start at boot; jupiter-arcade.service is
      # only started on demand (HA select), by which point this has run.
      before = [ "jupiter-arcade.service" ];
      path = [
        pkgs.coreutils
        pkgs.gnused
      ];
      serviceConfig = {
        Type = "oneshot";
        User = cfg.sessionUser;
        Group = "users";
      };
      script =
        let
          gameDirsFile = pkgs.writeText "pegasus-game_dirs.txt" ''
            # Managed by modules/desktop/arcade.nix (jupiter.arcade.gameDirs).
            # Hand-edits are overwritten on every boot/switch.
            ${lib.concatStringsSep "\n" cfg.gameDirs}
          '';
          settingsSeedFile = pkgs.writeText "pegasus-settings.txt" ''
            # Seeded by modules/desktop/arcade.nix; Pegasus rewrites this file
            # on exit with the user's UI choices, which then persist.
            general.theme: themes/${cfg.theme}
          '';
          # providers.<name>.enabled: false for every provider not opted
          # back in — appended (idempotently) at every boot.
          providerOffRegex = "^providers\\.(${lib.concatStringsSep "|" disabledPegasusProviders})\\.enabled:";
        in
        ''
          set -eu
          CONFIG_DIR="''${XDG_CONFIG_HOME:-/home/${cfg.sessionUser}/.config}/pegasus-frontend"
          mkdir -p "$CONFIG_DIR"

          install -m 0644 ${gameDirsFile} "$CONFIG_DIR/game_dirs.txt"

          # Seed the theme on first run only; drop legacy keys from the old
          # issue-30 stack (launcher.script / assets.directory /
          # collections.directory are not Pegasus settings — Pegasus itself
          # deletes them when it saves, but a stale seed may still carry them).
          SETTINGS="$CONFIG_DIR/settings.txt"
          if [ ! -f "$SETTINGS" ]; then
            install -m 0644 ${settingsSeedFile} "$SETTINGS"
          else
            sed -i '/^launcher\.script:/d;/^assets\.directory:/d;/^collections\.directory:/d' "$SETTINGS"
          fi

          # W4c provider defaults, self-healing at every boot: strip this
          # module's managed provider lines (both old disables AND any
          # drift the UI or a hand-edit wrote), then append the declared
          # set. Pegasus persists providers.*.enabled itself, so an
          # operator toggle survives until the next boot re-asserts the
          # DECLARED state — providersEnabled is the opt-in surface.
          # -E: the alternation is ERE.
          sed -Ei '/${providerOffRegex}/d' "$SETTINGS"
          printf '\n# providers: managed by modules/desktop/arcade.nix (jupiter.arcade.providersEnabled)\n' >> "$SETTINGS"
          cat ${providerDisableLines} >> "$SETTINGS"
        '';
    };
  };
}
