{
  config,
  lib,
  pkgs,
  ...
}:

# eXoDOS + eXoWin3x collection launcher for the TCx Wave kiosks.
#
# The ~1 TB eXo collection (7,200 DOS + ~1,140 Win3.x titles) lives on europa
# in the read-only `europa` ZFS pool (see hosts/europa/configuration.nix) and
# is exported RO over NFS (modules/storage/nas-nfs.nix). This module mounts it
# on each kiosk, layers a per-kiosk persisted overlayfs on top so game saves
# and first-run extractions land locally without ever writing back to europa,
# and generates Pegasus metadata from the collection's LaunchBox XML on every
# entry into the exodos session.
#
# The actual gamescope session unit (`jupiter-exodos.service`) is generated by
# modules/desktop/dashboard-gaming.nix's modeSpecs entry of the same name;
# this module owns everything AROUND that session: the mounts, the metadata
# generator, the exo-launch wrapper, and the gamer user's Pegasus config.
#
# See scripts/exo-to-pegasus.py (LaunchBox XML -> Pegasus metadata converter)
# and scripts/exo-launch.sh (per-game extract-if-needed + dosbox launcher) —
# both are kept in scripts/ for standalone testing and inlined into this
# module's closure via path interpolation so there's a single source of truth.
let
  cfg = config.jupiter.exodos;

  # The per-game launcher: extracts the matching .zip on first run (into the
  # overlay upper), then execs dosbox from <collection>/eXo/ as CWD so the
  # per-game dosbox.conf's [autoexec] relative mounts resolve correctly.
  # See scripts/exo-launch.sh for the full eXo layout explanation.
  exoLauncher = pkgs.writeShellScriptBin "exo-launch" (builtins.readFile ../../scripts/exo-launch.sh);

  # Privileged extraction helper invoked via `sudo -n` from exo-launch.
  # overlayfs's ovl_permission checks write on BOTH upper AND lower for
  # creates in directories that exist in both layers; the NFS lower's mode
  # bits are inconsistent and europa's pool is import-level read-only, so
  # non-root extraction dies with EACCES. Tried a setuid wrapper first
  # (security.wrappers) but bash drops setuid on exec, leaving the wrapper
  # unprivileged. Tried running the whole session as root, but gamescope
  # crashes on libseat_open_seat when User=root (no proper logind seat for
  # root on this kiosk). `sudo` is the right primitive: it sets full root
  # creds (not just the setuid bit), so bash doesn't drop, and the rest of
  # the session still runs unprivileged as `gamer` (preserving gamescope's
  # logind/DRM/seat access).
  # The script unzips then chowns back to the calling user so dosbox (as
  # gamer) can later write saves into the per-game dir — by then upper-only.
  exoExtractHelper = pkgs.writeShellScriptBin "exo-extract-helper" ''
    #!${pkgs.runtimeShell}
    # Invoked as root via: /run/wrappers/bin/sudo -n exo-extract-helper \
    #   <zip> <target-parent> <target-name> <chown-user> <chown-group>
    set -eu
    ZIP=$1
    TARGET_PARENT=$2
    TARGET_NAME=$3
    CHOWN_USER=$4
    CHOWN_GROUP=$5
    if [ ! -f "$ZIP" ]; then
      echo "exo-extract-helper: zip not found: $ZIP" >&2
      exit 1
    fi
    # Drop kernel dentry+inode caches before extraction. Overlayfs over NFS
    # accumulates stale positive dentries when an extraction is interrupted
    # (or when dosbox mounts a target that doesn't exist on the lower) — the
    # phantom entries make `[ -d ]` see a populated dir, and unzip -o tries
    # to unlink them as "old" files, getting ENOENT, erroring out (exit 50)
    # and leaving the game unlaunchable. drop_caches=2 clears dentries+inodes
    # only (pagecache stays); ~5s of cold-cache cost is acceptable for a
    # once-per-game extraction on a kiosk.
    echo 2 > /proc/sys/vm/drop_caches
    "${pkgs.unzip}/bin/unzip" -q -o "$ZIP" -d "$TARGET_PARENT"
    "${pkgs.coreutils}/bin/chown" -R "$CHOWN_USER:$CHOWN_GROUP" "$TARGET_PARENT/$TARGET_NAME"
    # TCx Wave kiosk touch panel is 1024x768 native. The eXoWin3x collection
    # ships with Win3.x configured for screen-size=640 (640x480), which makes
    # the Win3.x desktop smaller than the panel — dosbox scales it up and the
    # touch coordinates don't map 1:1. The bundled S3 driver supports up to
    # 1600x1200; bumping screen-size to 1024 (1024x768 256-color) makes the
    # desktop fill the panel and touch land where your finger does. Idempotent
    # sed — only edits the [DISPLAY] screen-size line, only if SYSTEM.INI
    # exists (so DOS extractions, which have no WINDOWS/SYSTEM.INI, are
    # untouched). Color depth (color-format=8) stays at 256.
    SYSINI="$TARGET_PARENT/$TARGET_NAME/WINDOWS/SYSTEM.INI"
    if [ -f "$SYSINI" ]; then
      "${pkgs.gnused}/bin/sed" -i 's/^screen-size=.*/screen-size=1024/' "$SYSINI"
    fi
  '';

  # Session launcher: seeds the gamer user's Pegasus config (game_dirs.txt +
  # settings.txt with our theme) on first launch (then preserves user edits via
  # impermanence), then execs pegasus-fe. Required because Pegasus shows "no
  # games" until game_dirs.txt tells it where the collection lives, and shows
  # the default "Pegasus Grid" theme until settings.txt points at ours. Done at
  # session start rather than via tmpfiles because tmpfiles `f` doesn't seed
  # from a Nix store path source on every systemd version, and because we want
  # the user's later UI edits preserved across reboots.
  exoPegasusSession = pkgs.writeShellScriptBin "exo-pegasus-session" ''
    #!${pkgs.runtimeShell}
    set -eu
    CONFIG_DIR="''${XDG_CONFIG_HOME:-$HOME/.config}/pegasus-frontend"
    mkdir -p "$CONFIG_DIR"
    # game_dirs.txt: where to find the collections.
    GAME_DIRS="$CONFIG_DIR/game_dirs.txt"
    if [ ! -f "$GAME_DIRS" ]; then
      install -m 0644 ${pegasusGameDirsFile} "$GAME_DIRS"
    fi
    # settings.txt: misc Pegasus settings. We seed only the theme; Pegasus
    # will append its own keys on first run (and we won't overwrite them).
    SETTINGS="$CONFIG_DIR/settings.txt"
    if [ ! -f "$SETTINGS" ]; then
      install -m 0644 ${pegasusSettingsFile} "$SETTINGS"
    fi
    exec ${pkgs.pegasus-frontend}/bin/pegasus-fe "$@"
  '';

  # Pegasus reads the collection directories from game_dirs.txt (one path per
  # line, `#` comments) — NOT from settings.txt. settings.txt holds theme and
  # other UI state; game_dirs.txt is the game-directories source of truth.
  # Seeded into the gamer user's home by exoPegasusSession above; edits persist
  # via impermanence so a user adding/removing dirs from Pegasus's Settings
  # menu survives kiosk reboots.
  pegasusGameDirsFile = pkgs.writeText "pegasus-game_dirs.txt" ''
    # Seeded by modules/desktop/exodos.nix. One directory per line; Pegasus
    # auto-discovers metadata.pegasus.txt in each. Safe to edit — changes
    # persist via impermanence.
    ${cfg.mergeMount}/eXoDOS
    ${cfg.mergeMount}/eXoWin3x
  '';

  # settings.txt seed: pins our custom theme so first-launch lands in
  # "jupiterOS arcade" instead of the default "Pegasus Grid".
  pegasusSettingsFile = pkgs.writeText "pegasus-settings.txt" ''
    # Seeded by modules/desktop/exodos.nix. Safe to edit; changes persist via
    # impermanence.
    theme: jupiteros-arcade
  '';

  # Custom Pegasus theme: "jupiterOS arcade". Functional minimalism — header
  # with our branding, horizontal platform bar (eXoDOS / eXoWin3x / Steam /
  # etc.), game grid below. Touch-friendly (large tap targets, no hover).
  # Pegasus themes are full QML apps; this one is intentionally simple so it's
  # easy to iterate on. Files live in the Nix store and are symlinked into
  # the gamer user's themes dir via tmpfiles.
  jupiterArcadeTheme = pkgs.stdenv.mkDerivation {
    name = "jupiteros-arcade-theme";
    src = ./jupiteros-arcade-theme;
    installPhase = ''
      runHook preInstall
      mkdir -p $out
      cp -r ./. $out/
      runHook postInstall
    '';
  };
in
{
  options.jupiter.exodos = {
    enable = lib.mkEnableOption ''
      eXoDOS + eXoWin3x collection launcher for a Cage kiosk:
      Pegasus frontend over an NFS-mounted, overlayfs-backed view of europa's
      read-only eXo collection. Designed for the TCx Wave kiosks; pull this in
      alongside modules/desktop/dashboard-gaming.nix's `exodos` modeSpecs entry
    '';

    nfsHost = lib.mkOption {
      type = lib.types.str;
      default = "10.1.1.2"; # europa's static LAN IP (hosts/europa/configuration.nix)
      description = ''
        NFS host serving the eXo collection. Defaults to europa's static DHCP
        reservation. Addressed by IP rather than hostname for the same reason
        every other cross-host wire in this repo is (the fleet has no DNS yet).
      '';
    };

    nfsPath = lib.mkOption {
      type = lib.types.str;
      default = "/mnt/europa/games";
      description = "Path on the NFS host to the eXo collection root.";
    };

    roMount = lib.mkOption {
      type = lib.types.str;
      default = "/mnt/europa-games";
      description = "Where to mount the read-only NFS export on this kiosk.";
    };

    mergeMount = lib.mkOption {
      type = lib.types.str;
      default = "/mnt/exo-games";
      description = ''
        Where to expose the merged overlayfs view (NFS lower + persisted RW
        upper). Pegasus reads the collections from here.
      '';
    };

    overlayUpper = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/exo-overlay/upper";
      description = ''
        Persisted overlay upper directory. Game saves and first-run
        extractions land here per-kiosk. Lives under /var/lib/exo-overlay,
        which is added to impermanence's extraDirectories below.
      '';
    };

    overlayWork = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/exo-overlay/work";
      description = "Persisted overlayfs workdir (required by overlayfs).";
    };

    sessionUser = lib.mkOption {
      type = lib.types.str;
      default = "gamer";
      description = ''
        User that owns the Pegasus config (~/.config/pegasus-frontend) and runs
        the session. Must match modules/desktop/dashboard-gaming.nix's
        sessionUser.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # --- Persisted overlay storage ------------------------------------------
    # extraDirectories is no-op on non-impermanent hosts (the dir just lives in
    # the regular root fs). On kiosks (the actual target) it bind-mounts from
    # /persist so saves + first-run extractions survive the erase-your-darlings
    # root wipe.
    jupiter.core.impermanence.extraDirectories = [ "/var/lib/exo-overlay" ];

    systemd.tmpfiles.rules = [
      "d /var/lib/exo-overlay 0755 root root -"
      "d ${cfg.overlayUpper} 0755 ${cfg.sessionUser} users -"
      "d ${cfg.overlayWork} 0755 ${cfg.sessionUser} users -"
      # Pegasus config dir; game_dirs.txt + settings.txt seeded on first
      # session launch by exoPegasusSession.
      "d /home/${cfg.sessionUser}/.config/pegasus-frontend 0755 ${cfg.sessionUser} users -"
      # Install the jupiterOS arcade theme as a symlink into the user themes
      # dir. L+ forces (re)create so a theme change in a future deploy
      # propagates without needing to wipe the user dir.
      "d /home/${cfg.sessionUser}/.config/pegasus-frontend/themes 0755 ${cfg.sessionUser} users -"
      "L+ /home/${cfg.sessionUser}/.config/pegasus-frontend/themes/jupiteros-arcade - - - - ${jupiterArcadeTheme}"
    ];

    # Allow the session user to run only the extraction helper as root with no
    # password. See exoExtractHelper above for why root is required.
    security.sudo.extraRules = [
      {
        users = [ cfg.sessionUser ];
        runAs = "root";
        commands = [
          {
            command = "${lib.getExe exoExtractHelper}";
            options = [ "NOPASSWD" ];
          }
        ];
      }
    ];

    # --- RO NFS mount of europa's eXo collection ----------------------------
    # `soft` so a dead europa doesn't hang dosbox reads forever; automount +
    # idle-timeout so the mount exists only while something is using it.
    fileSystems.${cfg.roMount} = {
      device = "${cfg.nfsHost}:${cfg.nfsPath}";
      fsType = "nfs";
      options = [
        "ro"
        "noatime"
        "soft"
        "noauto"
        "x-systemd.automount"
        "x-systemd.idle-timeout=10min"
        "x-systemd.mount-timeout=30"
      ];
    };

    # --- overlayfs: NFS RO lower + persisted RW upper -----------------------
    # Game saves and first-run extractions land in the upper layer; the
    # underlying eXo collection on europa stays pristine (read-only).
    # `depends` makes this mount unit Require+After the NFS mount unit.
    fileSystems.${cfg.mergeMount} = {
      device = "overlay";
      fsType = "overlay";
      options = [
        "lowerdir=${cfg.roMount}"
        "upperdir=${cfg.overlayUpper}"
        "workdir=${cfg.overlayWork}"
        "noauto"
        "x-systemd.automount"
        "x-systemd.idle-timeout=10min"
      ];
      depends = [ cfg.roMount ];
    };

    # --- Packages: launcher wrapper, frontend, unzip, dosboxen --------------
    # dosbox-staging (binary `dosbox`) for the DOS collection, dosbox-x for
    # Win3.x. Also pulled in via modules/gaming/console.nix's appCatalog when
    # the full gaming stack is enabled, but listed here too so this mode is
    # self-contained if a host ever opts into just exodos without the rest.
    environment.systemPackages = [
      exoLauncher
      exoPegasusSession
      exoExtractHelper
      pkgs.pegasus-frontend
      pkgs.unzip
      pkgs.dosbox-staging
      pkgs.dosbox-x
    ];

    # Per-emulator override confs, passed to dosbox AFTER the per-game conf
    # so our values win. See scripts/exo-launch.sh.
    # The TCx Wave panel is 1024x768 native (gamescope selects that mode).
    # eXo's per-game dosbox.conf ships with fullscreen=false and a huge
    # windowresolution (e.g. 2560x1920), which in dosbox-x shows a menu bar
    # that eats vertical space and squeezes the game into the remaining area
    # with ugly scaling. fullscreen=true hides the menu bar AND fills the
    # panel at native res — touch maps 1:1.
    environment.etc = {
      "exo/dosbox-override.conf".source = pkgs.writeText "dosbox-override.conf" ''
        [sdl]
        fullscreen=true
        fullresolution=1024x768
        windowresolution=1024x768
        output=openglnb
        autolock=true

        [render]
        aspect=true
      '';
      # Win3.x (dosbox-x) override also tries integration-mode mouse: dosbox-x
      # has a built-in "integration device" that can provide absolute-position
      # mouse events to a guest OS, which is what a touchscreen needs. If the
      # Win3.x mouse driver doesn't pick it up we'll need to install VBMOUSE
      # in each Win3.x image (planned follow-up); this is the cheap first try.
      "exo/dosbox-x-override.conf".source = pkgs.writeText "dosbox-x-override.conf" ''
        [sdl]
        fullscreen=true
        fullresolution=1024x768
        windowresolution=1024x768
        output=openglnb
        autolock=true
        mouse_emulation=integration
        usesystemcursor=true

        [cpu]
        integration device=true

        [render]
        aspect=true
      '';
    };

    # --- Metadata regenerator (runs once per session start) -----------------
    # Idempotent: scripts/exo-to-pegasus.py skips writing when its output is
    # newer than the source XML. Runs before the Pegasus session so Pegasus
    # always sees fresh metadata. Writes via the overlay, so the generated
    # metadata.pegasus.txt lands in the persisted upper.
    systemd.services.jupiter-exodos-metadata = {
      description = "eXo: regenerate Pegasus metadata from LaunchBox XML";
      path = [ pkgs.python3 ];
      serviceConfig = {
        Type = "oneshot";
        # No RemainAfterExit: we want this re-triggered every time the session
        # starts (Requires= below pulls it in), so a collection update on
        # europa is reflected on the next session entry.
      };
      unitConfig.RequiresMountsFor = "${cfg.mergeMount}";
      script = ''
        set -e
        ${pkgs.python3.interpreter} ${../../scripts/exo-to-pegasus.py} \
          --xml ${cfg.mergeMount}/eXoDOS/xml/MS-DOS.xml \
          --root ${cfg.mergeMount}/eXoDOS \
          --collection eXoDOS \
          --shortname dos \
          --emulator dosbox
        ${pkgs.python3.interpreter} ${../../scripts/exo-to-pegasus.py} \
          --xml '${cfg.mergeMount}/eXoWin3x/xml/Windows 3x.xml' \
          --root ${cfg.mergeMount}/eXoWin3x \
          --collection eXoWin3x \
          --shortname win3x \
          --emulator dosbox-x \
          --rewrite eXoWin3X:eXoWin3x
      '';
    };

    # --- Session unit wiring ------------------------------------------------
    # The jupiter-exodos.service unit itself is generated by
    # modules/desktop/dashboard-gaming.nix's modeSpecs entry; this just adds
    # the mount + metadata deps so the session always launches into a
    # mounted, metadata-ready collection. Gated on the mode's own enable so
    # this is inert on hosts that haven't turned the mode on.
    systemd.services."jupiter-exodos" = lib.mkIf config.jupiter.dashboardGaming.modes.exodos.enable {
      requires = [ "jupiter-exodos-metadata.service" ];
      after = [ "jupiter-exodos-metadata.service" ];
      unitConfig.RequiresMountsFor = "${cfg.mergeMount}";
    };
  };
}
