{
  config,
  lib,
  pkgs,
  ...
}:

# eXoDOS + eXoWin3x collection launcher for the TCx Wave kiosks.
#
# The ~1 TB eXo collection (7,200 DOS + ~1,140 Win3.x titles) lives on europa
# in the read-only `europa` ZFS pool (see hosts/europa/configuration.nix) and
# is exported RO over NFS (modules/storage/nas-nfs.nix). This module mounts it
# on each kiosk, layers a per-kiosk persisted overlayfs on top so game saves
# and first-run extractions land locally without ever writing back to europa,
# and generates Pegasus metadata from the collection's LaunchBox XML on every
# entry into the exodos session.
#
# The actual gamescope session unit (`jupiter-exodos.service`) is generated by
# modules/desktop/dashboard-gaming.nix's modeSpecs entry of the same name;
# this module owns everything AROUND that session: the mounts, the metadata
# generator, the exo-launch wrapper, and the gamer user's Pegasus config.
#
# See scripts/exo-to-pegasus.py (LaunchBox XML -> Pegasus metadata converter)
# and scripts/exo-launch.sh (per-game extract-if-needed + dosbox launcher) —
# both are kept in scripts/ for standalone testing and inlined into this
# module's closure via path interpolation so there's a single source of truth.
let
  cfg = config.jupiter.exodos;

  # The per-game launcher: extracts the matching .zip on first run (into the
  # overlay upper), then execs dosbox from <collection>/eXo/ as CWD so the
  # per-game dosbox.conf's [autoexec] relative mounts resolve correctly.
  # See scripts/exo-launch.sh for the full eXo layout explanation.
  exoLauncher = pkgs.writeShellScriptBin "exo-launch" (builtins.readFile ../../scripts/exo-launch.sh);

  # Session launcher: seeds the gamer user's Pegasus settings.txt on first
  # launch (then preserves user edits via impermanence), then execs pegasus-fe.
  # Required because Pegasus shows "no games" until settings.txt's
  # `directories:` line tells it where the collection lives. Done at session
  # start rather than via tmpfiles because tmpfiles `f` doesn't seed from a
  # Nix store path source on every systemd version, and because we want the
  # user's later UI edits (theme, favorites) preserved across reboots.
  exoPegasusSession = pkgs.writeShellScriptBin "exo-pegasus-session" ''
    #!${pkgs.runtimeShell}
    set -eu
    CONFIG_DIR="''${XDG_CONFIG_HOME:-$HOME/.config}/pegasus-frontend"
    SETTINGS="$CONFIG_DIR/settings.txt"
    if [ ! -f "$SETTINGS" ]; then
      mkdir -p "$CONFIG_DIR"
      install -m 0644 ${pegasusSettingsFile} "$SETTINGS"
    fi
    exec ${pkgs.pegasus-frontend}/bin/pegasus-fe "$@"
  '';

  # Minimum Pegasus settings: just point at the two merged collection dirs.
  # Pegasus auto-discovers metadata.pegasus.txt under each. Seeded into the
  # gamer user's home by exoPegasusSession above; edits persist via
  # impermanence so favorites/theme choices survive kiosk reboots.
  pegasusSettingsFile = pkgs.writeText "pegasus-settings.txt" ''
    # Seeded by modules/desktop/exodos.nix. Safe to edit; changes persist via
    # impermanence. Pegasus auto-discovers metadata.pegasus.txt in each.
    directories: ${cfg.mergeMount}/eXoDOS, ${cfg.mergeMount}/eXoWin3x
  '';
in
{
  options.jupiter.exodos = {
    enable = lib.mkEnableOption ''
      eXoDOS + eXoWin3x collection launcher for a Cage kiosk:
      Pegasus frontend over an NFS-mounted, overlayfs-backed view of europa's
      read-only eXo collection. Designed for the TCx Wave kiosks; pull this in
      alongside modules/desktop/dashboard-gaming.nix's `exodos` modeSpecs entry
    '';

    nfsHost = lib.mkOption {
      type = lib.types.str;
      default = "10.1.1.2"; # europa's static LAN IP (hosts/europa/configuration.nix)
      description = ''
        NFS host serving the eXo collection. Defaults to europa's static DHCP
        reservation. Addressed by IP rather than hostname for the same reason
        every other cross-host wire in this repo is (the fleet has no DNS yet).
      '';
    };

    nfsPath = lib.mkOption {
      type = lib.types.str;
      default = "/mnt/europa/games";
      description = "Path on the NFS host to the eXo collection root.";
    };

    roMount = lib.mkOption {
      type = lib.types.str;
      default = "/mnt/europa-games";
      description = "Where to mount the read-only NFS export on this kiosk.";
    };

    mergeMount = lib.mkOption {
      type = lib.types.str;
      default = "/mnt/exo-games";
      description = ''
        Where to expose the merged overlayfs view (NFS lower + persisted RW
        upper). Pegasus reads the collections from here.
      '';
    };

    overlayUpper = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/exo-overlay/upper";
      description = ''
        Persisted overlay upper directory. Game saves and first-run
        extractions land here per-kiosk. Lives under /var/lib/exo-overlay,
        which is added to impermanence's extraDirectories below.
      '';
    };

    overlayWork = lib.mkOption {
      type = lib.types.str;
      default = "/var/lib/exo-overlay/work";
      description = "Persisted overlayfs workdir (required by overlayfs).";
    };

    sessionUser = lib.mkOption {
      type = lib.types.str;
      default = "gamer";
      description = ''
        User that owns the Pegasus config (~/.config/pegasus-frontend) and runs
        the session. Must match modules/desktop/dashboard-gaming.nix's
        sessionUser.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # --- Persisted overlay storage ------------------------------------------
    # extraDirectories is no-op on non-impermanent hosts (the dir just lives in
    # the regular root fs). On kiosks (the actual target) it bind-mounts from
    # /persist so saves + first-run extractions survive the erase-your-darlings
    # root wipe.
    jupiter.core.impermanence.extraDirectories = [ "/var/lib/exo-overlay" ];

    systemd.tmpfiles.rules = [
      "d /var/lib/exo-overlay 0755 root root -"
      "d ${cfg.overlayUpper} 0755 root root -"
      "d ${cfg.overlayWork} 0755 root root -"
      # Pegasus config dir; settings.txt is seeded on first session launch by
      # exoPegasusSession (not here — see the wrapper's comment for why).
      "d /home/${cfg.sessionUser}/.config/pegasus-frontend 0755 ${cfg.sessionUser} users -"
    ];

    # --- RO NFS mount of europa's eXo collection ----------------------------
    # `soft` so a dead europa doesn't hang dosbox reads forever; automount +
    # idle-timeout so the mount exists only while something is using it.
    fileSystems.${cfg.roMount} = {
      device = "${cfg.nfsHost}:${cfg.nfsPath}";
      fsType = "nfs";
      options = [
        "ro"
        "noatime"
        "soft"
        "noauto"
        "x-systemd.automount"
        "x-systemd.idle-timeout=10min"
        "x-systemd.mount-timeout=30"
      ];
    };

    # --- overlayfs: NFS RO lower + persisted RW upper -----------------------
    # Game saves and first-run extractions land in the upper layer; the
    # underlying eXo collection on europa stays pristine (read-only).
    # `depends` makes this mount unit Require+After the NFS mount unit.
    fileSystems.${cfg.mergeMount} = {
      device = "overlay";
      fsType = "overlay";
      options = [
        "lowerdir=${cfg.roMount}"
        "upperdir=${cfg.overlayUpper}"
        "workdir=${cfg.overlayWork}"
        "noauto"
        "x-systemd.automount"
        "x-systemd.idle-timeout=10min"
      ];
      depends = [ cfg.roMount ];
    };

    # --- Packages: launcher wrapper, frontend, unzip, dosboxen --------------
    # dosbox-staging (binary `dosbox`) for the DOS collection, dosbox-x for
    # Win3.x. Also pulled in via modules/gaming/console.nix's appCatalog when
    # the full gaming stack is enabled, but listed here too so this mode is
    # self-contained if a host ever opts into just exodos without the rest.
    environment.systemPackages = [
      exoLauncher
      exoPegasusSession
      pkgs.pegasus-frontend
      pkgs.unzip
      pkgs.dosbox-staging
      pkgs.dosbox-x
    ];

    # --- Metadata regenerator (runs once per session start) -----------------
    # Idempotent: scripts/exo-to-pegasus.py skips writing when its output is
    # newer than the source XML. Runs before the Pegasus session so Pegasus
    # always sees fresh metadata. Writes via the overlay, so the generated
    # metadata.pegasus.txt lands in the persisted upper.
    systemd.services.jupiter-exodos-metadata = {
      description = "eXo: regenerate Pegasus metadata from LaunchBox XML";
      path = [ pkgs.python3 ];
      serviceConfig = {
        Type = "oneshot";
        # No RemainAfterExit: we want this re-triggered every time the session
        # starts (Requires= below pulls it in), so a collection update on
        # europa is reflected on the next session entry.
      };
      unitConfig.RequiresMountsFor = "${cfg.mergeMount}";
      script = ''
        set -e
        ${pkgs.python3.interpreter} ${../../scripts/exo-to-pegasus.py} \
          --xml ${cfg.mergeMount}/eXoDOS/xml/MS-DOS.xml \
          --root ${cfg.mergeMount}/eXoDOS \
          --collection eXoDOS \
          --shortname dos \
          --emulator dosbox
        ${pkgs.python3.interpreter} ${../../scripts/exo-to-pegasus.py} \
          --xml '${cfg.mergeMount}/eXoWin3x/xml/Windows 3x.xml' \
          --root ${cfg.mergeMount}/eXoWin3x \
          --collection eXoWin3x \
          --shortname win3x \
          --emulator dosbox-x \
          --rewrite eXoWin3X:eXoWin3x
      '';
    };

    # --- Session unit wiring ------------------------------------------------
    # The jupiter-exodos.service unit itself is generated by
    # modules/desktop/dashboard-gaming.nix's modeSpecs entry; this just adds
    # the mount + metadata deps so the session always launches into a
    # mounted, metadata-ready collection. Gated on the mode's own enable so
    # this is inert on hosts that haven't turned the mode on.
    systemd.services."jupiter-exodos" = lib.mkIf config.jupiter.dashboardGaming.modes.exodos.enable {
      requires = [ "jupiter-exodos-metadata.service" ];
      after = [ "jupiter-exodos-metadata.service" ];
      unitConfig.RequiresMountsFor = "${cfg.mergeMount}";
    };
  };
}
