# Configuration template for the Wyze Cams running wz_mini_hacks
# Simply drop this onto the SD card in the root directory.

[ENABLE_RTSP]
# Enable RTSP server (very useful for bringing them into Home Assistant)
ENABLE_RTSP="true"

[RTSP_SERVER]
RTSP_PORT="8554"
RTSP_USERNAME="admin"
RTSP_PASSWORD="password"

[ENABLE_SSH]
# Enable dropbear SSH for remote management
ENABLE_SSH="true"
SSH_PASSWORD="root"
