# Canonical network facts for the home site — the single source of truth for
# VLANs, subnets, the resolver address, and the internal DNS records.
#
# Consumed by BOTH:
#   * the NixOS resolver config (hosts/lenovo -> jupiter.dns), and
#   * the terranix UniFi stack (terraform/unifi/default.nix),
# so the two can never drift. This is plain data (no module system), which is
# why both a NixOS module and a terranix module can `import` it directly.
#
# Verified against the live UDM Pro: Cameras = VLAN 2 / 192.168.3.0/24,
# IOT = VLAN 3 / 192.168.2.0/24.
{
  # The single internal resolver every client (and DHCP) points at.
  resolver = "10.1.1.20";
  gateway = "10.1.1.1";
  domain = "home.jupiter.au";

  # L2/L3 networks. `networkCidr` is the network address (for DNS access-control
  # / allow-lists); `gatewayCidr` is the gateway address with prefix (what the
  # UniFi `unifi_network.subnet` field actually wants). vlan = null is untagged.
  networks = {
    default = {
      name = "Default";
      vlan = null;
      networkCidr = "10.1.1.0/24";
      gatewayCidr = "10.1.1.1/24";
      dhcpStart = "10.1.1.6";
      dhcpStop = "10.1.1.254";
    };
    cameras = {
      name = "Cameras";
      vlan = 2;
      networkCidr = "192.168.3.0/24";
      gatewayCidr = "192.168.3.1/24";
      dhcpStart = "192.168.3.6";
      dhcpStop = "192.168.3.254";
    };
    iot = {
      name = "IOT";
      vlan = 3;
      networkCidr = "192.168.2.0/24";
      gatewayCidr = "192.168.2.1/24";
      dhcpStart = "192.168.2.6";
      dhcpStop = "192.168.2.254";
    };
  };

  # headscale mesh ranges — also permitted to query the resolver.
  meshCidrs = [
    "100.64.0.0/10"
    "fd7a:115c:a1e0::/48"
  ];

  # Central data store (the NAS): the single hub every host's persistent state
  # replicates to, and the only host with offsite egress. Hosts that opt into
  # jupiter.backup authorize this key for the NAS to pull as root.
  # The public key is generated by `make gen-secrets` (private half → sops) and
  # read from the committed file here — never hand-set.
  backupHub = {
    host = "nas";
    address = "10.1.1.2";
    syncoidPublicKey = builtins.replaceStrings [ "\n" ] [ "" ] (
      builtins.readFile ../secrets/syncoid_ed25519.pub
    );
  };

  # Public zone + the Cloudflare Tunnel. The ingress map drives BOTH the
  # cloudflared config on lenovo (hostname → local backend) and the public
  # proxied-CNAME records in terraform/cloudflare (hostname → the tunnel), so the
  # two never drift.
  publicZone = "jupiter.au";
  tunnel = {
    id = "aa1088b8-a0e1-4073-8567-6a9bf5fb4bd7";
    ingress = {
      "headscale.jupiter.au" = "http://127.0.0.1:8080";
      "n8n.jupiter.au" = "http://127.0.0.1:5678";
      "ha.jupiter.au" = "http://127.0.0.1:8123";
    };
  };

  # Static internal A/PTR records for the split-horizon zone.
  records = {
    "gateway.home.jupiter.au" = "10.1.1.1";
    "nas.home.jupiter.au" = "10.1.1.2";
    "lenovo.home.jupiter.au" = "10.1.1.20";
    "elitedesk.home.jupiter.au" = "10.1.1.21"; # diskless compute; syslog/Loki sink
    "ha.home.jupiter.au" = "10.1.1.72";
    "smokeping.home.jupiter.au" = "10.1.1.221";
  };
}
