import { Theme } from "../theme.slint";

export component StatusBar inherits Rectangle {
    in property <string> title: "";
    in property <string> air-quality: "BREATHABLE";
    in property <string> clock: "";

    height: 60px;
    border-width: 1px;
    border-color: Theme.primary-dim;
    background: Theme.background;

    HorizontalLayout {
        padding: 10px;
        spacing: 16px;
        Text {
            text: root.title;
            color: Theme.primary;
            font-family: Theme.font-family;
            font-size: 20px;
            horizontal-stretch: 1;
            vertical-alignment: center;
        }
        Text {
            text: root.air-quality;
            color: root.air-quality == "CONTAMINATED" ? Theme.alert : Theme.primary-dim;
            font-family: Theme.font-family;
            vertical-alignment: center;
        }
        Text {
            text: root.clock;
            color: Theme.primary-dim;
            font-family: Theme.font-family;
            vertical-alignment: center;
        }
    }
}
