#!/usr/bin/env python3
"""LaunchBox XML -> Pegasus metadata converter for the eXo collections.

Reads a LaunchBox <Game> XML (eXoDOS's xml/MS-DOS.xml or eXoWin3x's
xml/Windows 3x.xml), emits a Pegasus metadata.pegasus.txt at the
collection root. Each game's `file:` points at its per-game dosbox.conf
(relative to the collection root); the collection-level `launch` invokes
dosbox-staging (DOS) or dosbox-x (Win3.x) with that conf, run from the
game's own directory so each eXo dosbox.conf's [autoexec] (relative
mounts, .bat launcher) works unmodified.

Idempotent: skips writing when the existing output is newer than the
source XML unless --force is passed. Run by jupiter-exodos-metadata.service
(modules/desktop/exodos.nix) on every entry into the exodos session.

Pegasus metadata syntax: https://pegasus-frontend.org/docs/user-guide/meta-files/
"""
import argparse
import os
import sys
import xml.etree.ElementTree as ET


def game_dir_from_application_path(application_path: str, rewrites: list) -> str:
    # LaunchBox stores Windows-style paths (eXo\eXoDOS\!dos\StuntIsl\foo.bat);
    # Pegasus wants POSIX paths, and we anchor on the game's directory so the
    # per-game dosbox.conf (sibling of the .bat launcher) resolves.
    posix_path = application_path.replace("\\", "/")
    # LaunchBox ran on Windows (case-insensitive FS), so its stored paths don't
    # always match the on-disk case of the eXo collection as extracted on a
    # case-sensitive Linux FS. eXoWin3x is the worst offender: the XML says
    # eXoWin3X everywhere but the extracted dir is eXoWin3x. Each --rewrite
    # OLD:NEW applies a literal substring replacement before we dirname().
    for old, new in rewrites:
        posix_path = posix_path.replace(old, new)
    return os.path.dirname(posix_path)


def text_or_empty(parent: ET.Element, tag: str) -> str:
    el = parent.find(tag)
    if el is None or el.text is None:
        return ""
    return el.text.strip()


def bool_field(parent: ET.Element, tag: str) -> bool:
    return text_or_empty(parent, tag).lower() == "true"


def release_year(release_date: str) -> str:
    # LaunchBox stores full ISO (1992-01-01T00:00:00-06:00); Pegasus accepts
    # YYYY-MM-DD. Take the date prefix; if absent, fall back to nothing.
    if not release_date:
        return ""
    return release_date[:10]


def community_rating(star_str: str) -> str:
    # LaunchBox CommunityStarRating is 0..5; Pegasus rating is 0..100%.
    try:
        stars = float(star_str)
    except (TypeError, ValueError):
        return ""
    if stars <= 0:
        return ""
    return f"{round(stars * 20)}%"


def collapse_ws(text: str) -> str:
    # Pegasus summary/description are single logical lines; flatten internal
    # newlines and runs of whitespace so a stray \n in LaunchBox's <Notes>
    # can't terminate the entry early.
    return " ".join(text.split())


def genres_list(genre_field: str) -> list:
    # LaunchBox uses ';' as the separator (e.g. "Cards / Tiles;Puzzle;Sports").
    if not genre_field:
        return []
    return [g.strip() for g in genre_field.split(";") if g.strip()]


def escape_value(value: str) -> str:
    # Pegasus values run to end-of-line; strip a leading space so "key: value"
    # never becomes "key:  value" (which would make the value start with a
    # space, parsed as a list-item continuation). Internal colons are fine.
    return value.lstrip()


def render_entry(
    title: str,
    file_rel: str,
    developer: str,
    publisher: str,
    genres: list,
    release: str,
    summary: str,
    rating: str,
    favorite: bool,
    lb_id: str,
    manual_rel: str,
) -> list:
    lines = [f"game: {escape_value(title)}"]
    if file_rel:
        lines.append(f"file: {file_rel}")
    if developer:
        lines.append(f"developer: {escape_value(developer)}")
    if publisher:
        lines.append(f"publisher: {escape_value(publisher)}")
    for g in genres:
        lines.append(f"genre: {escape_value(g)}")
    if release:
        lines.append(f"release: {release}")
    if summary:
        lines.append(f"summary: {escape_value(summary)}")
    if rating:
        lines.append(f"rating: {rating}")
    if favorite:
        lines.append("x-favorite: true")
    if lb_id:
        lines.append(f"x-lb-id: {lb_id}")
    if manual_rel:
        lines.append(f"x-manual: {escape_value(manual_rel)}")
    lines.append("")  # blank separator between entries
    return lines


def convert(xml_path: str, root: str, collection: str, shortname: str, emulator: str, rewrites: list) -> int:
    tree = ET.parse(xml_path)
    root_el = tree.getroot()

    out_lines = [
        f"# Generated by scripts/exo-to-pegasus.py from {os.path.basename(xml_path)}.",
        f"# Do not edit by hand \u2014 regenerate via jupiter-exodos-metadata.service.",
        f"# Collection root: {root}",
        f"# Emulator: {emulator}",
        "",
        f"collection: {collection}",
        f"shortname: {shortname}",
        # The eXo launch flow: each game's dosbox.conf [autoexec] mounts C: at
        # `.\eXoDOS\<gamedir>` (relative to dosbox's CWD = the collection's eXo/
        # dir, NOT the game dir), so the bundled game files must be unzipped
        # into `<collection>/eXo/eXoDOS/<gamedir>/` first. `exo-launch`
        # (modules/desktop/exodos.nix) takes the per-game dosbox.conf path,
        # extracts the matching zip on first run (into the persisted overlay
        # upper), then execs dosbox from the right CWD. {file.path} is the
        # per-game dosbox.conf path, evaluated per-entry by Pegasus.
        f"launch: exo-launch {emulator} {{file.path}}",
        "",
    ]

    emitted = 0
    skipped_hidden = 0
    skipped_no_path = 0

    for game in root_el.findall("Game"):
        if bool_field(game, "Hide") or bool_field(game, "Broken"):
            skipped_hidden += 1
            continue

        application_path = text_or_empty(game, "ApplicationPath")
        if not application_path:
            skipped_no_path += 1
            continue

        title = text_or_empty(game, "Title") or "(untitled)"
        game_dir = game_dir_from_application_path(application_path, rewrites)
        # The per-game dosbox.conf is the launch anchor: it carries the
        # cycles/cpu/sound/autoexec settings eXo tuned per title. If absent,
        # Pegasus simply hides the game (its own filter), which is the right
        # behavior for the handful of titles without one.
        file_rel = f"{game_dir}/dosbox.conf" if game_dir else "dosbox.conf"

        out_lines.extend(
            render_entry(
                title=title,
                file_rel=file_rel,
                developer=text_or_empty(game, "Developer"),
                publisher=text_or_empty(game, "Publisher"),
                genres=genres_list(text_or_empty(game, "Genre")),
                release=release_year(text_or_empty(game, "ReleaseDate")),
                summary=collapse_ws(text_or_empty(game, "Notes")),
                rating=community_rating(text_or_empty(game, "CommunityStarRating")),
                favorite=bool_field(game, "Favorite"),
                lb_id=text_or_empty(game, "ID"),
                manual_rel=text_or_empty(game, "ManualPath"),
            )
        )
        emitted += 1

    return out_lines, emitted, skipped_hidden, skipped_no_path


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--xml", required=True, help="Path to LaunchBox MS-DOS.xml / Windows 3x.xml")
    p.add_argument("--root", required=True, help="Collection root (metadata.pegasus.txt lives here)")
    p.add_argument("--collection", required=True, help="Pegasus collection name, e.g. 'eXoDOS'")
    p.add_argument("--shortname", required=True, help="Pegasus shortname, e.g. 'dos' or 'win3x'")
    p.add_argument(
        "--emulator",
        required=True,
        choices=["dosbox", "dosbox-x"],
        help="Binary name (dosbox=dosbox-staging, dosbox-x=dosbox-x)",
    )
    p.add_argument(
        "--rewrite",
        action="append",
        default=[],
        metavar="OLD:NEW",
        help=(
            "Literal substring rewrite applied to each game's POSIX-converted "
            "ApplicationPath (repeatable). Use to fix Windows-vs-Linux case "
            "mismatches, e.g. --rewrite eXoWin3X:eXoWin3x"
        ),
    )
    p.add_argument("--force", action="store_true", help="Regenerate even if output is newer than XML")
    args = p.parse_args()

    rewrites = [tuple(r.split(":", 1)) for r in args.rewrite]
    if any(len(r) != 2 for r in rewrites):
        p.error("--rewrite values must be OLD:NEW (got one without a colon)")

    output_path = os.path.join(args.root, "metadata.pegasus.txt")

    if not args.force and os.path.exists(output_path):
        xml_mtime = os.path.getmtime(args.xml)
        out_mtime = os.path.getmtime(output_path)
        if out_mtime >= xml_mtime:
            print(
                f"skip: {output_path} is newer than {args.xml} (use --force to regenerate)",
                file=sys.stderr,
            )
            return 0

    out_lines, emitted, skipped_hidden, skipped_no_path = convert(
        xml_path=args.xml,
        root=args.root,
        collection=args.collection,
        shortname=args.shortname,
        emulator=args.emulator,
        rewrites=rewrites,
    )

    os.makedirs(args.root, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines))

    print(
        f"wrote {output_path}: {emitted} games emitted, "
        f"{skipped_hidden} hidden/broken skipped, {skipped_no_path} pathless skipped",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
