#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Niro Copilot BYOK → DeepSeek, for the manual find-only workflow.
# Values land in GitHub secrets/variables only (this is CI configuration), so
# nothing is written to a local .env — the repository does not ignore one.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Niro + DeepSeek setup"

# ── Stage 1: DeepSeek API key → GitHub secret ─────────────────────────────
stage "DeepSeek: API key"
say "Niro's Copilot BYOK runs on DeepSeek. The workflow's guard refuses to"
say "start without this key, and the key is only ever read by that workflow."
open_url "https://platform.deepseek.com/api_keys"
step "Sign in, create an API key (name it e.g. niro-ci), and copy its value."
step "You will paste it below; the prompt hides what you type."
ask_secret COPILOT_PROVIDER_API_KEY "Paste the DeepSeek API key (hidden):"
if [[ -n "$COPILOT_PROVIDER_API_KEY" ]]; then
  set_secret COPILOT_PROVIDER_API_KEY "$COPILOT_PROVIDER_API_KEY"
else
  warn "nothing entered; leaving any existing secret untouched"
  SKIPPED+=("DeepSeek API key — gh secret set COPILOT_PROVIDER_API_KEY")
fi

# ── Stage 2: provider variables (non-secret) ──────────────────────────────
stage "Copilot BYOK: provider variables"
say "These point Copilot CLI at DeepSeek's OpenAI-compatible API. They are"
say "not secrets, so they live as repository variables."
note "deepseek-flash is the DeepSeek-V4.1-Flash model: tool calls, 1M context."
set_var COPILOT_PROVIDER_BASE_URL "https://api.deepseek.com"
set_var COPILOT_PROVIDER_TYPE "openai"
set_var COPILOT_MODEL "deepseek-flash"

# ── Stage 3 (optional): second approval gate ──────────────────────────────
stage "GitHub environment: required reviewers (optional)"
say "The workflow runs in the 'niro-autonomous' environment. Reviewers there"
say "make every dispatch need an approval on top of the dispatch itself."
say "Enter usernames, or press Enter with an empty line to skip."
ask REVIEWERS "GitHub usernames, comma-separated (empty to skip):"
if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "gh not ready; skipping environment update"
elif [[ -n "${REVIEWERS//[[:space:]]/}" ]]; then
  reviewers_json="["
  first=1
  IFS=',' read -r -a _logins <<<"$REVIEWERS"
  for login in "${_logins[@]}"; do
    login="${login//[[:space:]]/}"
    [[ -n "$login" ]] || continue
    id="$(gh api "users/$login" --jq .id 2>/dev/null || true)"
    if [[ -z "$id" ]]; then
      warn "cannot resolve GitHub user '$login'; skipping"
      continue
    fi
    (( first )) || reviewers_json+=","
    reviewers_json+="{\"type\":\"User\",\"id\":$id}"
    first=0
  done
  reviewers_json+="]"
  if [[ "$reviewers_json" = "[]" ]]; then
    note "no valid usernames; skipping"
  elif printf '{"reviewers":%s,"deployment_branch_policy":null}' "$reviewers_json" |
    gh api --method PUT "repos/{owner}/{repo}/environments/niro-autonomous" --input - >/dev/null; then
    printf '  %s✓%s niro-autonomous now requires reviewer approval\n' "$GREEN" "$RESET"
  else
    warn "could not update the environment; set it in repo Settings → Environments"
  fi
else
  note "skipped — re-run this wizard any time to add reviewers"
fi

# ── Stage 4: verify + dispatch the bootstrap run ──────────────────────────
stage "Verify, then dispatch the bootstrap run"
say "Checking names and non-secret values only — never the key itself."
if gh secret list --json name --jq '.[].name' 2>/dev/null | grep -qx COPILOT_PROVIDER_API_KEY; then
  printf '  %s✓%s secret COPILOT_PROVIDER_API_KEY present\n' "$GREEN" "$RESET"
else
  warn "secret COPILOT_PROVIDER_API_KEY missing"
fi
for v in COPILOT_PROVIDER_BASE_URL COPILOT_PROVIDER_TYPE COPILOT_MODEL; do
  printf '  %s✓%s %s=%s\n' "$GREEN" "$RESET" "$v" "$(gh variable get "$v" 2>/dev/null || echo '<missing>')"
done
pause "Press Enter to continue"
ask GOAL "Goal for the bootstrap run (Enter for the default):"
GOAL="${GOAL:-Test the arcade-webapp rescan, inventory and collection endpoints}"
if confirm "Dispatch the narrow bootstrap run now (spends DeepSeek tokens)?"; then
  if gh workflow run niro-find.yml --ref main \
    -f agent=copilot \
    -f goal="$GOAL"; then
    printf '  %s✓%s dispatched. Watch it:\n' "$GREEN" "$RESET"
    note "  gh run list --workflow=niro-find.yml"
    note "  gh run watch \$(gh run list --workflow=niro-find.yml --limit 1 --json databaseId --jq '.[0].databaseId')"
  else
    warn "dispatch failed; run it by hand: gh workflow run niro-find.yml -f agent=copilot"
  fi
else
  note "not dispatched. When ready:"
  note "  gh workflow run niro-find.yml -f agent=copilot -f goal=\"$GOAL\""
fi

finish

