{ config, pkgs, ... }:

{
  imports = [
    ../../modules/common-stateful.nix
    ./disko.nix # OS SSD layout (destructive, OS disk only)
    ../../modules/storage/zfs-nas.nix # imports tank (new) + the "europa" archive zpool + samba — pool name predates and inspired this host's name
    ../../modules/storage/sanoid.nix # snapshots on tank
    ../../modules/storage/zfs-tuning.nix # ARC/kernel/samba perf for this hardware
    ../../modules/storage/nas-nfs.nix # NFS exports to the network
    ../../modules/storage/iscsi.nix # iSCSI block export of zvols to callisto
    ../../modules/storage/replication.nix # pulls server state datasets here (syncoid)
    ../../modules/storage/smart-monitoring.nix # SMART health checks on tank/backup's physical disks
    ../../modules/network/nas-bond.nix # optional 2×1GbE LACP (opt-in below)
    ../../modules/services/backups.nix # restic offsite (jupiter.backups.paths below)
    ../../modules/services/attic-server.nix # binary cache for the "rebuild the world" build server (jupiter.services.attic below)
  ];

  networking.hostName = "europa";
  networking.hostId = "deadbeef"; # Stable per-host 8-char hex, required for ZFS

  # Confirmed HPE MicroServer Gen10, AMD Opteron X3216 (see
  # modules/storage/zfs-tuning.nix's hardware notes) — a "Cato" APU on the
  # Puma core, ISA-equivalent to Jaguar, which GCC targets as btver2. Safe to
  # target for the "rebuild the world" build-server workflow (see
  # docs/roadmap.md).
  jupiter.build.microarch = "btver2";

  # RobCo/Fallout boot branding (GRUB theme, MOTD).
  jupiter.branding.enable = true;

  # The backup hub stays conservative: plain nixpkgs kernel (not the fleet-wide
  # CachyOS default from modules/common.nix) and no exposure to chaotic-nyx's
  # binary cache/overlay/registry. The chaotic flake module is still injected
  # uniformly via flake.nix's mkHost (per its lexical-closure design), but
  # these three toggles neutralize its effect here.
  #
  # Pinned to zfs's declared max-supported kernel series (see the comment in
  # modules/storage/zfs-profiles.nix), not linuxPackages_latest — europa is
  # the ZFS NAS, so a kernel newer than zfs actually supports is a hard
  # breakage here, not just a missed optimization. Bump alongside that file.
  boot.kernelPackages = pkgs.linuxPackages_7_0;
  chaotic.nyx.cache.enable = false;
  chaotic.nyx.overlay.enable = false;
  chaotic.nyx.registry.enable = false;

  # Static identity below the DHCP pool (.6-.254) so iSCSI/NFS clients have a
  # stable target. DNS (europa.home.jupiter.au) points here. Uses OUR resolver
  # via common.nix default (10.1.1.20). When the LACP bond is enabled, move
  # this address onto bond0.
  networking.useDHCP = false;
  networking.interfaces.enp2s0f0.ipv4.addresses = [
    {
      address = "10.1.1.2";
      prefixLength = 24;
    }
  ];
  networking.defaultGateway = "10.1.1.1";

  # Aggregate the two 1GbE ports once the UniFi switch-side LACP is configured.
  # Leave disabled until then (default DHCP on a single port keeps it reachable).
  jupiter.nas.bond.enable = false;

  # iSCSI block exports for the diskless callisto (DB + Loki persistence).
  # Network IQN scheme: iqn.2026-06.au.jupiter:<host>. Must match callisto's
  # services.openiscsi.name (see hosts/callisto/configuration.nix).
  jupiter.nas.iscsi = {
    enable = true;
    luns = [
      {
        name = "db";
        dev = "/dev/zvol/rpool/db";
        initiatorIqn = "iqn.2026-06.au.jupiter:callisto";
      }
      {
        name = "loki";
        dev = "/dev/zvol/rpool/loki";
        initiatorIqn = "iqn.2026-06.au.jupiter:callisto";
      }
    ];
  };

  # The NAS is the fleet's data hub. It pulls every replicate-enabled host's
  # state here hourly via syncoid — the SOURCES are derived automatically from
  # each host's jupiter.backup in flake.nix (backupHubModule), so no host is
  # enumerated here. Just provide the pull key + enable the puller.
  # See modules/storage/replication.nix for the one-time SSH-key provisioning.
  sops.secrets.syncoid_ssh_key = { }; # keypair generated by `make gen-secrets`
  jupiter.replication = {
    enable = true;
    sshKeyPath = config.sops.secrets.syncoid_ssh_key.path;
  };

  # Offsite (restic -> cloud): tank/personal plus ALL replicated host state under
  # tank/backups (so any future host the hub pulls is covered without edits
  # here). Media/surveillance/downloads/archive stay on tank's mirror; the frozen
  # europa archive is the user's separate long-term project.
  jupiter.backups.paths = [
    "/tank/personal"
    "/tank/backups"
  ];

  # Binary cache for the "rebuild the world" build server (docs/roadmap.md) —
  # storage lives on tank/services/attic, not backed up offsite (reproducible
  # bulk state), and is exposed at attic.jupiter.au via the Cloudflare Tunnel.
  jupiter.services.attic.enable = true;

  environment.systemPackages = with pkgs; [
    zfs
    samba
    sanoid # provides syncoid too, for manual runs
  ];

  # The NAS is the Syncthing hub: store the canonical synced copy on tank/personal
  # (mirror + sanoid 'important' + restic offsite) instead of the OS disk, so the
  # roaming personal data is fully protected. Folders created in the WebUI should
  # live under this path (now the default).
  jupiter.services.syncthing = {
    enable = true;
    dataDir = "/tank/personal";
  };

  # SMART self-tests + health checks across every attached disk (OS SSD +
  # tank/backup mirror members) — europa is the only host with physical
  # spinning/SSD storage worth watching (see modules/storage/smart-monitoring.nix).
  jupiter.storage.smartMonitoring.enable = true;
}
